version: "2"

linters:
  default: all
  disable:
    - nilnil
    - mnd
    - wrapcheck
    - err113
    - noinlineerr
    - paralleltest
    - testpackage
    - exhaustruct
    - goconst
    - varnamelen
    - nonamedreturns
    - nlreturn
    - wsl_v5

    #
    # Redundant
    #
    - cyclop    # revive
    - funlen    # revive
    - gocognit  # revive
    - gocyclo   # revive
    - lll       # revive
    - wsl       # wsl_v5

  settings:

    depguard:
      rules:
        yaml:
          files:
            - '!**/yamlpatch/patcher.go'
          deny:
            - pkg: gopkg.in/yaml.v2
              desc: yaml.v2 is deprecated for new code in favor of yaml.v3

    errcheck:
      check-type-assertions: true

    funcorder:
      struct-method: true

    gocritic:
      enable-all: true
      disabled-checks:
        - paramTypeCombine
        - sloppyReassign
        - commentedOutCode
        - whyNoLint

    govet:
      disable:
        - fieldalignment
      enable-all: true

    maintidx:
      # raise this after refactoring
      under: 18

    misspell:
      locale: US

    nlreturn:
      block-size: 5

    nolintlint:
      require-explanation: false  # don't require an explanation for nolint directives
      require-specific: false     # don't require nolint directives to be specific about which linter is being skipped
      allow-unused: false         # report any unused nolint directives

    recvcheck:
      exclusions:
        # methods from time.Duration and pflag.Value don't use the same type of receiver.
        - DurationWithDays.Set
        - DurationWithDays.String
        - DurationWithDays.Type
        - DurationWithDays.Hours
        - DurationWithDays.Minutes
        - DurationWithDays.Seconds
        - DurationWithDays.Milliseconds
        - DurationWithDays.Nanoseconds

    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          arguments:
            # lower this after refactoring
            - 46
        - name: cyclomatic
          arguments:
            # lower this after refactoring
            - 43
        - name: flag-parameter
          disabled: true
        - name: function-length
          arguments:
            # lower this after refactoring
            - 104
            - 198
        - name: line-length-limit
          arguments:
            # lower this after refactoring
            - 114
        - name: unnecessary-stmt
          disabled: true
        - name: useless-break
          disabled: true

    staticcheck:
      checks:
        - all

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:

      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows declaration'

      - linters:
          - revive
        path: (.+)/(.+)_test.go
        text: 'line-length-limit: .*'

      - linters:
          - revive
        path: trace/trace.go
        text: "defer: recover must be called inside a deferred function"

      - linters:
          - forbidigo
        path: downloader/examples/

    paths:
      - yamlpatch/merge.go
      - yamlpatch/merge_test.go
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/crowdsecurity)
        - prefix(github.com/crowdsecurity/go-cs-lib)

  exclusions:
    paths:
      - yamlpatch/merge.go
      - yamlpatch/merge_test.go
      - third_party$
      - builtin$
      - examples$
